version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: mathfacts-api:local
    container_name: backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - AWS_REGION=us-east-1
      - AWS_PROFILE=mathfacts
    volumes:
      - ~/.aws:/root/.aws:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: ./frontend
    image: mathfacts-web:local
    container_name: frontend
    restart: unless-stopped
    environment:
      - API_ORIGIN=http://backend:8080
    depends_on:
      - backend
    ports:
      - "8081:80"          # Nginx listens on 80
