server:
  port: 8080
logging:
  level:
    root: INFO
    com.rp.mathfacts: DEBUG
    software.amazon.awssdk: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,loggers
spring:
  application:
    name: mathfacts
  datasource:
    url: jdbc:h2:mem:mathdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
app:
  aws:
    region: us-east-1
    s3Bucket: spelling-audio-rp
    presignSeconds: 86400
  polly:
    voiceId: Joanna
    engine: standard
