spring:
  application:
    name: mathfacts
  datasource:
    url: jdbc:postgresql://localhost:5432/mathdb
    username: mathuser
    password: mathpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
