name: Test, Build and Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run tests
        run: mvn test --batch-mode

  deploy:
    name: Build, Push to ECR & Deploy to ECS
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker tags
        run: |
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          echo "ECR_URI=${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build -t $ECR_URI:$IMAGE_TAG .

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_URI:$IMAGE_TAG

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2.3.4
        with:
          task-definition: .github/workflows/ecs/mathfacts_task.json
          service-name: mathfacts-service
          cluster-name: mathfacts
          wait-for-service-stability: true
