name: Test, Build and Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run tests
        run: mvn test --batch-mode

  deploy:
    name: Build, Push to ECR & Deploy to ECS
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker tags
        run: |
          echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "REG=${{ secrets.ECR_REGISTRY }}" >> $GITHUB_ENV
          echo "API_REPO=${{ secrets.ECR_REPOSITORY_API }}" >> $GITHUB_ENV
          echo "WEB_REPO=${{ secrets.ECR_REPOSITORY_WEB }}" >> $GITHUB_ENV

      # Build & push backend (root Dockerfile)
      - name: Build backend image
        run: docker build -t $REG/$API_REPO:$TAG .

      - name: Push backend image
        run: docker push $REG/$API_REPO:$TAG

      # Build & push frontend (frontend/Dockerfile)
      - name: Build frontend image
        run: docker build -t $REG/$WEB_REPO:$TAG -f frontend/Dockerfile frontend

      - name: Push frontend image
        run: docker push $REG/$WEB_REPO:$TAG

      # Render and deploy API task
      - name: Render API task def
        id: render_api
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .github/workflows/ecs/mathfacts_task.json
          container-name: mathfacts-container
          image: ${{ env.REG }}/${{ env.REPO }}:${{ env.TAG }}

      - name: Deploy API
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2.3.4
        with:
          task-definition: ${{ steps.render_api.outputs.task-definition }}
          service: mathfacts-service
          cluster: mathfacts
          wait-for-service-stability: true


#      # Render and deploy WEB task
#      - name: Render WEB task def
#        id: render_web
#        uses: aws-actions/amazon-ecs-render-task-definition@v1
#        with:
#          task-definition: .github/workflows/ecs/mathfacts_web_task.json
#          container-name: mathfacts-web          # must match your task def
#          image: ${{ env.REG }}/${{ env.WEB_REPO }}:${{ env.TAG }}
#
#      - name: Deploy WEB
#        uses: aws-actions/amazon-ecs-deploy-task-definition@v2.3.4
#        with:
#          task-definition: ${{ steps.render_web.outputs.task-definition }}
#          service: mathfacts-web
#          cluster: mathfacts
#          wait-for-service-stability: true